apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: given-halibut-java-springboot
  janus-idp.io/tekton: given-halibut-java-springboot
  backstage.io/kubernetes-id: given-halibut-java-springboot
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: given-halibut-java-springboot
resources: 
- deployment.yaml
- route.yaml
- service.yaml
